name: Build and release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Build and release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export K3S_VERSION="$(cat k3s.version)"
          echo "K3S version: ${K3S_VERSION}"

          export RELEASE_EXISTS=$(gh release view latest &> /dev/null; echo $?)

          if [[ "${RELEASE_EXISTS}" -eq 0 ]]; then
            if gh release view latest --json assets -q '.assets[].name' | grep -q "k3s-${K3S_VERSION}"; then
              echo "Version ${K3S_VERSION} is already present in the release, exiting..."
              exit 0
            fi
          fi

          echo "Building k3s-${K3S_VERSION} sysext"
          ./build.sh

          if [[ "${RELEASE_EXISTS}" -eq 0 ]]; then
            echo "Generating SHA256SUMS"
            (
              cd dist/ && \
              gh release download --pattern '*.sha256' && \
              for file in *.sha256; do cat "$file"; done > SHA256SUMS
            )

            echo "Uploading assets to the release"
            gh release delete-asset latest SHA256SUMS
            gh release upload latest dist/k3s-${K3S_VERSION}* dist/SHA256SUMS
          else
            cp dist/*.sha256 dist/SHA256SUMS

            echo "Creating release"
            gh release create --title latest latest dist/*
          fi
